// generated by @sebspark/bruno-to-k6
import { sleep } from 'k6'
import { run as simpleGet } from './requests/simple-get.js'
import { run as simplePost } from './requests/simple-post.js'
import { run as simplePut } from './requests/simple-put.js'
import { run as simpleDelete } from './requests/simple-delete.js'

const ENV = {}
const VARS = {}

export default function () {
  simpleGet({ ENV, VARS })
  simplePost({ ENV, VARS })
  simplePut({ ENV, VARS })
  simpleDelete({ ENV, VARS })
  sleep(1)
}
