// generated by @sebspark/bruno-to-k6
import http from 'k6/http'
import { check } from 'k6'
import { usingBruno } from '@sebspark/bruno-to-k6/runtime'

export function run({ ENV, VARS } = {}) {
  const { bru, req, parse } = usingBruno({ env: ENV, vars: VARS })

  // GET https://example.test/oauth
  const res = http.request(
    'GET',
    parse.url('https://example.test/oauth'),
    undefined,
    parse.params({headers: {Authorization: 'Bearer ${bru.oauth2Token(ENV, 'credentials')}'}}),
  )
  check(res, {'status < 400': r => r.status < 400})
}
