// generated by @sebspark/bruno-to-k6
import http from 'k6/http'
import { check } from 'k6'
import { usingBruno } from '@sebspark/bruno-to-k6/runtime'

export function run({ ENV, VARS } = {}) {
  const { bru, req, parse } = usingBruno({ env: ENV, vars: VARS })

  // POST https://example.test/sparql
  const res = http.request(
    'POST',
    parse.url('https://example.test/sparql'),
    parse.body('SELECT ?s ?p ?o\nWHERE {\n  ?s ?p ?o\n}\nLIMIT 10'),
  )
  check(res, {'status < 400': r => r.status < 400})
}
