// generated by @sebspark/bruno-to-k6
import http from 'k6/http'
import { check } from 'k6'
import { usingBruno } from '@sebspark/bruno-to-k6/runtime'

export function run({ ENV, VARS } = {}) {
  const { bru, req, parse } = usingBruno({ env: ENV, vars: VARS })

  // GET https://example.test/headers
  const res = http.request(
    'GET',
    parse.url('https://example.test/headers'),
    undefined,
    parse.params({headers: {'X-Trace-Id': 'abc-123', Accept: 'application/json'}}),
  )
  check(res, {'status < 400': r => r.status < 400})
}
