// generated by @sebspark/bruno-to-k6
import http from 'k6/http'
import { sleep, check } from 'k6'
import { usingBruno } from '@sebspark/bruno-to-k6/runtime'


const ENV = {
  host: 'example.com'
}
const VARS = {}

export default function () {
  const { bru, req, parse } = usingBruno({ env: ENV, vars: VARS })

  // GET http://{{host}}
  const res = http.request(
    'GET',
    parse.url('http://{{host}}'),
  )
  check(res, {'status < 400': r => r.status < 400})

  sleep(1)
}
