// generated by @sebspark/bruno-to-k6
import { sleep } from 'k6'
import { run as headersBasic } from './requests/headers-basic.js'
import { run as bodySparql } from './requests/body-sparql.js'
import { run as queryParams } from './requests/query-params.js'
import { run as bodyJsonRaw } from './requests/body-json-raw.js'
import { run as bodyTextRaw } from './requests/body-text-raw.js'
import { run as bodyFormUrlencoded } from './requests/body-form-urlencoded.js'
import { run as bodyMultipartForm } from './requests/body-multipart-form.js'
import { run as bodyGraphql } from './requests/body-graphql.js'
import { run as authBearer } from './requests/auth-bearer.js'
import { run as authBasic } from './requests/auth-basic.js'
import { run as authApikey } from './requests/auth-apikey.js'
import { run as scriptsPrePost } from './requests/scripts-pre-post.js'
import { run as authDigest } from './requests/auth-digest.js'
import { run as authOauth } from './requests/auth-oauth.js'

const ENV = {}
const VARS = {}

export default function () {
  headersBasic({ ENV, VARS })
  bodySparql({ ENV, VARS })
  queryParams({ ENV, VARS })
  bodyJsonRaw({ ENV, VARS })
  bodyTextRaw({ ENV, VARS })
  bodyFormUrlencoded({ ENV, VARS })
  bodyMultipartForm({ ENV, VARS })
  bodyGraphql({ ENV, VARS })
  authBearer({ ENV, VARS })
  authBasic({ ENV, VARS })
  authApikey({ ENV, VARS })
  scriptsPrePost({ ENV, VARS })
  authDigest({ ENV, VARS })
  authOauth({ ENV, VARS })
  sleep(1)
}
