// generated by @sebspark/bruno-to-k6
import http from 'k6/http'
import { sleep, check } from 'k6'
import { usingBruno } from '@sebspark/bruno-to-k6/runtime'


const ENV = {}
const VARS = {}

export default function () {
  const { bru, req, parse } = usingBruno({ env: ENV, vars: VARS })

  // GET https://example.test
  const res = http.request(
    'GET',
    parse.url('https://example.test'),
  )
  check(res, {'status < 400': r => r.status < 400})

  // POST https://example.test/items
  const res2 = http.request(
    'POST',
    parse.url('https://example.test/items'),
    parse.body({name: 'Widget'}),
    parse.params({headers: {'Content-Type': 'application/json'}}),
  )
  check(res2, {'status < 400': r => r.status < 400})

  // PUT https://example.test/items/123
  const res3 = http.request(
    'PUT',
    parse.url('https://example.test/items/123'),
    parse.body({name: 'Widget v2'}),
    parse.params({headers: {'Content-Type': 'application/json'}}),
  )
  check(res3, {'status < 400': r => r.status < 400})

  // DELETE https://example.test/items/123
  const res4 = http.request(
    'DELETE',
    parse.url('https://example.test/items/123'),
  )
  check(res4, {'status < 400': r => r.status < 400})

  sleep(1)
}
