// generated by @sebspark/bruno-to-k6
import http from 'k6/http'
import { sleep, check } from 'k6'
import { usingBruno } from '@sebspark/bruno-to-k6/runtime'


const ENV = {}
const VARS = {}

export default function () {
  const { bru, req, parse } = usingBruno({ env: ENV, vars: VARS })

  // PUT https://example.test/items/123
  const res = http.request(
    'PUT',
    parse.url('https://example.test/items/123'),
    parse.body({name: 'Widget v2'}),
    parse.params({headers: {'Content-Type': 'application/json'}}),
  )
  check(res, {'status < 400': r => r.status < 400})

  sleep(1)
}
