// generated by @sebspark/bruno-to-k6
import { sleep } from 'k6'
import { run as root } from './requests/root.js'

const ENV = {
  host: 'example.com'
}
const VARS = {}

export default function () {
  root({ ENV, VARS })
  sleep(1)
}
