// generated by @sebspark/bruno-to-k6
import http from 'k6/http'
import { sleep, check } from 'k6'
import { usingBruno } from '@sebspark/bruno-to-k6/runtime'


const ENV = {}
const VARS = {}

export default function () {
  const { bru, req, parse } = usingBruno({ env: ENV, vars: VARS })

  // POST https://example.test/graphql
  const res = http.request(
    'POST',
    parse.url('https://example.test/graphql'),
    parse.body({query: 'query Q($id: String!) {\n  me {\n    id\n  }\n}', variables: '{\n  "id": "1"\n}'}),
    parse.params({headers: {'Content-Type': 'application/json'}}),
  )
  check(res, {'status < 400': r => r.status < 400})

  sleep(1)
}
