// generated by @sebspark/bruno-to-k6
import http from 'k6/http'
import { sleep, check } from 'k6'
import { usingBruno } from '@sebspark/bruno-to-k6/runtime'


const ENV = {}
const VARS = {}

export default function () {
  const { bru, req, parse } = usingBruno({ env: ENV, vars: VARS })

  // GET https://example.com/
  const res = http.request(
    'GET',
    parse.url('https://example.com/'),
  )
  check(res, {'status < 400': r => r.status < 400})

  // GET https://example.com/users
  const res2 = http.request(
    'GET',
    parse.url('https://example.com/users'),
  )
  check(res2, {'status < 400': r => r.status < 400})

  // GET https://example.com/users/:id/posts
  const res3 = http.request(
    'GET',
    parse.url('https://example.com/users/45/posts'),
  )
  check(res3, {'status < 400': r => r.status < 400})

  sleep(1)
}
