// generated by @sebspark/bruno-to-k6
import http from 'k6/http'
import { check } from 'k6'
import { usingBruno } from '@sebspark/bruno-to-k6/runtime'

export function run({ ENV, VARS } = {}) {
  const { bru, req, parse } = usingBruno({ env: ENV, vars: VARS })

  // GET http://{{host}}
  const res = http.request(
    'GET',
    parse.url('http://{{host}}'),
  )
  check(res, {'status < 400': r => r.status < 400})
}
