// generated by @sebspark/bruno-to-k6
import { sleep } from 'k6'
import { run as root } from './requests/root.js'
import { run as list } from './requests/users/list.js'
import { run as list2 } from './requests/users/posts/list.js'

const ENV = {}
const VARS = {}

export default function () {
  root({ ENV, VARS })
  list({ ENV, VARS })
  list2({ ENV, VARS })
  sleep(1)
}
